name: Build Flutter APK and Email

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install dependencies
        run: flutter pub get
        working-directory: emoji_table_app_new

      - name: Build APK
        run: flutter build apk --release
        working-directory: emoji_table_app_new

      - name: Email APK
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'New Flutter APK Build'
          to: supritam310797@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: 'The latest APK build is attached.'
          attachments: emoji_table_app_new/build/app/outputs/flutter-apk/app-release.apk 